# NUMPY - NUMERICAL PYTHON
- IS CORE OF CALCULATION IN PYTHON PACKAGE

In [14]:
import numpy as np

In [31]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [36]:
print(a)
print('dimension:',a.ndim)
print('size:', a.size)
print('datatype of element', a.dtype)

[1 2 3]
dimension: 1
size: 3
datatype of element int32


In [22]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
np.zeros((2,2))#create an array full of zeros

array([[0., 0.],
       [0., 0.]])

# linspace
- linspace function and arange funtion both are similar because linspace also  create sequance of evenly spaced value within a defined interval

- it also gives  value in specified range
- this is litle be different frome arange function because arange return be step value but here be mebtioned the breakpoints.
- syntax - linspace(start,stop,num=50,endpoint=true,retstep=false,dtype=none,axis=0)
- num =5 means number of element in the array

In [26]:
np.linspace(10,50,5) # linspace (start,end,no.of elements)

array([10., 20., 30., 40., 50.])

In [42]:
np.linspace(1,100,num=5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [43]:
np.linspace(1,100,num=5,endpoint=False)# endpoint means don't considered 100

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [44]:
np.linspace(1,100,num=4,retstep=True)

(array([  1.,  34.,  67., 100.]), 33.0)

In [27]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
#create 6 dimentional array with arange having 6 element in 1 dimention
d= np.arange(6).reshape(1,1,1,1,1,6)


In [29]:
np.arange(6).reshape(1,1,1,1,1,6)

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

In [30]:
print(d)
print('dimension:',d.ndim)#no.of dimensions
print('size:',d.size)# size
print('shape',d.shape)
print('element type',d.dtype)#Data type

[[[[[[0 1 2 3 4 5]]]]]]
dimension: 6
size: 6
shape (1, 1, 1, 1, 1, 6)
element type int32


# manipulation in Array
- RESHAPE ARRAY
- Dimension shuffling
- joining array
- spiliting arrays
- add & remove elements to array
- arrange arrays
- resize # it can be resize the accordind to shape, total number of array element
  

# RESHAPE & RESIZE
- this is gives new shap to array without chane the data of array
- numpy.reshape(array,shape,order)'order means c( raw vs function,f(column vs  function,)
- returned ndarray element may be copy of the original array elements
- second syntax array.reshape(shape.order)

## RESIZE :
- this function return new array with the specified shape
- it will be changed the data of the array 
- numpy.resize(arrayname.shape)
- resize is nothing but change the total number of element present in  the array while changing the shape of the array.

In [8]:
import numpy as np


In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.shape

(10,)

In [12]:
np.resize(a,(4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
a = np.array([[1,2,3,4],[2,3,4,5]])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

#Arange
- creates array of evenly spaced  value
- it will return numeric value in specified range
- syntax ([stop]) start and step is optional butwe can defined in same column
- it is return array of evenly space value

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(20,dtype= "complex")

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [22]:
np.arange(1,10,2,dtype=float)

array([1., 3., 5., 7., 9.])

In [7]:
np.arange(10)

NameError: name 'np' is not defined